version: "2"

linters:
  default: standard
  enable:
    - copyloopvar
    - errorlint
    - gosec
    - misspell
    - nilerr
    - revive
    - unconvert
    - unparam
    - wastedassign
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln

formatters:
  enable:
    - gofmt
    - goimports
