FROM alpine:3.22 AS certificates
RUN apk add --no-cache ca-certificates

FROM scratch
ARG TARGETPLATFORM
COPY --from=certificates /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY $TARGETPLATFORM/ripen /ripen

USER 65532:65532

VOLUME ["/data"]
ENTRYPOINT ["/ripen"]
CMD ["daemon", "--config", "/config/policy.yaml"]
